name: Bug 反馈
description: "报告一个 Bug 或异常行为"
title: "[Bug] "
labels: ["bug"]
body:
  - type: checkboxes
    id: ensure
    attributes:
      label: 提交前确认
      description: 请确保已完成以下步骤，否则 Issue 可能会被直接关闭。
      options:
        - label: 我已搜索过现有 Issue，确认没有重复问题
          required: true
        - label: 如果是前端问题，我已在无痕模式（禁用所有扩展）下复现，问题仍然存在
          required: true
        - label: 此Issue仅包含一个Bug反馈，而不是多个Bug反馈
          required: true
  - type: dropdown
    id: upstream-interface
    attributes:
      label: 上游接口类型
      description: 上游是以什么接口接入 Octopus 的？(添加渠道时选的什么渠道类型)
      options:
        - OpenAI Chat Completions
        - OpenAI Responses
        - Anthropic Messages
        - Google Gemini
    validations:
      required: true
  - type: dropdown
    id: client-interface
    attributes:
      label: 客户端接口类型
      description: 客户端是以什么格式请求的Octopus?
      options:
        - OpenAI Chat Completions
        - OpenAI Responses
        - Anthropic Messages
    validations:
      required: true
  - type: input
    id: client-version
    attributes:
      label: 客户端版本号
      description: 请提供客户端的详细版本号
      placeholder: "例如: Cursor 0.48.9, Claude Desktop 1.2.3"
    validations:
      required: true
  - type: textarea
    id: client-config
    attributes:
      label: 客户端配置
      description: 请提供客户端的配置（截图或者直接粘贴配置文件,请不要以文件的形式上传配置文件）
    validations:
      required: true
  - type: input
    id: browser-version
    attributes:
      label: 浏览器版本号
      description: 如果是前端BUG请提供浏览器的详细版本号
      placeholder: "例如: Chrome 120.0.xxx, Firefox 120.0.xxx"
  - type: textarea
    attributes:
      label: 问题描述
      description: 请详细描述遇到的问题。如涉及前端问题，请务必在无痕模式下截图，否则 Issue 可能会被关闭。
      placeholder: 清晰描述你遇到了什么问题...
    validations:
      required: true
  - type: textarea
    attributes:
      label: 复现步骤
      description: 请提供能够复现该问题的详细步骤
      placeholder: |
        1. 进入 '...'
        2. 点击 '...'
        3. 滚动至 '...'
        4. 出现错误
    validations:
      required: true
  - type: textarea
    attributes:
      label: WEB日志
      description: WEB端的日志截图（请直接粘贴图片）
    validations:
      required: true
  - type: textarea
    attributes:
      label: 后端日志
      description: 后端的日志（请直接粘贴日志）
      render: shell
    validations:
      required: true
