// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package netobs

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tcpConnHostKey struct {
	_     structs.HostLayout
	Daddr uint32
	Dport uint16
	Pad   uint16
}

type tcpConnHostStat struct {
	_            structs.HostLayout
	Connects     uint64
	Fails        uint64
	LatencySumNs uint64
	LatencyCount uint64
}

type tcpConnInflightVal struct {
	_    structs.HostLayout
	Key  tcpConnHostKey
	TsNs uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	tcpConnMapConnectHits         = "connect_hits"
	tcpConnMapHostStats           = "host_stats"
	tcpConnMapInflight            = "inflight"
	tcpConnProgHandleConnectEnter = "handle_connect_enter"
	tcpConnProgHandleConnectExit  = "handle_connect_exit"
)

// loadTcpConn returns the embedded CollectionSpec for tcpConn.
func loadTcpConn() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpConnBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcpConn: %w", err)
	}

	return spec, err
}

// loadTcpConnObjects loads tcpConn and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcpConnObjects
//	*tcpConnPrograms
//	*tcpConnMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpConnObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcpConn()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpConnSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpConnSpecs struct {
	tcpConnProgramSpecs
	tcpConnMapSpecs
	tcpConnVariableSpecs
}

// tcpConnProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpConnProgramSpecs struct {
	HandleConnectEnter *ebpf.ProgramSpec `ebpf:"handle_connect_enter"`
	HandleConnectExit  *ebpf.ProgramSpec `ebpf:"handle_connect_exit"`
}

// tcpConnMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpConnMapSpecs struct {
	ConnectHits *ebpf.MapSpec `ebpf:"connect_hits"`
	HostStats   *ebpf.MapSpec `ebpf:"host_stats"`
	Inflight    *ebpf.MapSpec `ebpf:"inflight"`
}

// tcpConnVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpConnVariableSpecs struct {
}

// tcpConnObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpConnObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpConnObjects struct {
	tcpConnPrograms
	tcpConnMaps
	tcpConnVariables
}

func (o *tcpConnObjects) Close() error {
	return _TcpConnClose(
		&o.tcpConnPrograms,
		&o.tcpConnMaps,
	)
}

// tcpConnMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpConnObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpConnMaps struct {
	ConnectHits *ebpf.Map `ebpf:"connect_hits"`
	HostStats   *ebpf.Map `ebpf:"host_stats"`
	Inflight    *ebpf.Map `ebpf:"inflight"`
}

func (m *tcpConnMaps) Close() error {
	return _TcpConnClose(
		m.ConnectHits,
		m.HostStats,
		m.Inflight,
	)
}

// tcpConnVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcpConnObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpConnVariables struct {
}

// tcpConnPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpConnObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpConnPrograms struct {
	HandleConnectEnter *ebpf.Program `ebpf:"handle_connect_enter"`
	HandleConnectExit  *ebpf.Program `ebpf:"handle_connect_exit"`
}

func (p *tcpConnPrograms) Close() error {
	return _TcpConnClose(
		p.HandleConnectEnter,
		p.HandleConnectExit,
	)
}

func _TcpConnClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcpconn_bpfeb.o
var _TcpConnBytes []byte
