// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package netobs

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	tcpConnMapConnectHits    = "connect_hits"
	tcpConnMapHostHits       = "host_hits"
	tcpConnProgHandleConnect = "handle_connect"
)

// loadTcpConn returns the embedded CollectionSpec for tcpConn.
func loadTcpConn() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpConnBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcpConn: %w", err)
	}

	return spec, err
}

// loadTcpConnObjects loads tcpConn and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcpConnObjects
//	*tcpConnPrograms
//	*tcpConnMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpConnObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcpConn()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpConnSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpConnSpecs struct {
	tcpConnProgramSpecs
	tcpConnMapSpecs
	tcpConnVariableSpecs
}

// tcpConnProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpConnProgramSpecs struct {
	HandleConnect *ebpf.ProgramSpec `ebpf:"handle_connect"`
}

// tcpConnMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpConnMapSpecs struct {
	ConnectHits *ebpf.MapSpec `ebpf:"connect_hits"`
	HostHits    *ebpf.MapSpec `ebpf:"host_hits"`
}

// tcpConnVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpConnVariableSpecs struct {
}

// tcpConnObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpConnObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpConnObjects struct {
	tcpConnPrograms
	tcpConnMaps
	tcpConnVariables
}

func (o *tcpConnObjects) Close() error {
	return _TcpConnClose(
		&o.tcpConnPrograms,
		&o.tcpConnMaps,
	)
}

// tcpConnMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpConnObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpConnMaps struct {
	ConnectHits *ebpf.Map `ebpf:"connect_hits"`
	HostHits    *ebpf.Map `ebpf:"host_hits"`
}

func (m *tcpConnMaps) Close() error {
	return _TcpConnClose(
		m.ConnectHits,
		m.HostHits,
	)
}

// tcpConnVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcpConnObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpConnVariables struct {
}

// tcpConnPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpConnObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpConnPrograms struct {
	HandleConnect *ebpf.Program `ebpf:"handle_connect"`
}

func (p *tcpConnPrograms) Close() error {
	return _TcpConnClose(
		p.HandleConnect,
	)
}

func _TcpConnClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcpconn_bpfel.o
var _TcpConnBytes []byte
