// Code generated by bpf2go; DO NOT EDIT.

package netobs

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tcpConnSockopsAsyncInflight struct {
	_    structs.HostLayout
	Key  tcpConnSockopsHostKey
	TsNs uint64
}

type tcpConnSockopsConnStats struct {
	_          structs.HostLayout
	SrttUs     uint64
	Count      uint64
	Retrans    uint64
	AsyncFails uint64
}

type tcpConnSockopsHostKey struct {
	_     structs.HostLayout
	Daddr uint32
	Dport uint16
	Pad   uint16
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	tcpConnSockopsMapInflightMap    = "inflight_map"
	tcpConnSockopsMapSrttMap        = "srtt_map"
	tcpConnSockopsProgHandleSockops = "handle_sockops"
)

// loadTcpConnSockops returns the embedded CollectionSpec for tcpConnSockops.
func loadTcpConnSockops() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpConnSockopsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcpConnSockops: %w", err)
	}

	return spec, err
}

// loadTcpConnSockopsObjects loads tcpConnSockops and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcpConnSockopsObjects
//	*tcpConnSockopsPrograms
//	*tcpConnSockopsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpConnSockopsObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcpConnSockops()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpConnSockopsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpConnSockopsSpecs struct {
	tcpConnSockopsProgramSpecs
	tcpConnSockopsMapSpecs
	tcpConnSockopsVariableSpecs
}

// tcpConnSockopsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpConnSockopsProgramSpecs struct {
	HandleSockops *ebpf.ProgramSpec `ebpf:"handle_sockops"`
}

// tcpConnSockopsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpConnSockopsMapSpecs struct {
	InflightMap *ebpf.MapSpec `ebpf:"inflight_map"`
	SrttMap     *ebpf.MapSpec `ebpf:"srtt_map"`
}

// tcpConnSockopsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpConnSockopsVariableSpecs struct {
}

// tcpConnSockopsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpConnSockopsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpConnSockopsObjects struct {
	tcpConnSockopsPrograms
	tcpConnSockopsMaps
	tcpConnSockopsVariables
}

func (o *tcpConnSockopsObjects) Close() error {
	return _TcpConnSockopsClose(
		&o.tcpConnSockopsPrograms,
		&o.tcpConnSockopsMaps,
	)
}

// tcpConnSockopsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpConnSockopsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpConnSockopsMaps struct {
	InflightMap *ebpf.Map `ebpf:"inflight_map"`
	SrttMap     *ebpf.Map `ebpf:"srtt_map"`
}

func (m *tcpConnSockopsMaps) Close() error {
	return _TcpConnSockopsClose(
		m.InflightMap,
		m.SrttMap,
	)
}

// tcpConnSockopsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcpConnSockopsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpConnSockopsVariables struct {
}

// tcpConnSockopsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpConnSockopsObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpConnSockopsPrograms struct {
	HandleSockops *ebpf.Program `ebpf:"handle_sockops"`
}

func (p *tcpConnSockopsPrograms) Close() error {
	return _TcpConnSockopsClose(
		p.HandleSockops,
	)
}

func _TcpConnSockopsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcpconnsockops_bpf.o
var _TcpConnSockopsBytes []byte
